spring.application.name=temvaga.ai

#google
#spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com
#spring.ai.openai.chat.options.model=gemini-2.5-flash-lite
#spring.ai.openai.chat.completions-path=/v1beta/openai/chat/completions
#spring.ai.openai.api-key=${GOOGLE-API-KEY}

#local ollama
spring.ai.openai.chat.base-url=http://localhost:11434
spring.ai.openai.chat.options.model=qwen3.5:9b
spring.ai.openai.api-key=not_use_yet

#Azuna config
adzuna.app.id=${ADZUNA_APP_ID}
adzuna.app.key=${ADZUNA_APP_KEY}

#Message config
telegram.chat.id=${TELEGRAM_CHAT_ID}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
discord.webhook.url=${DISCORD_WEBHOOK_URL:url}